{
 "title": "Picom - Scenario 2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Picom Server Deployment CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "alias": "Sum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" }
     ]
    },
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" }
     ]
    }
   ]
  },
  {
   "title": "Server Instances",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(code_ok_total)" }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rpc_duration_ms_count{exported_service=\"MyService.ProcImage\"}[30s])",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/picom-client-(.*)/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pod" }
     ]
    }
   ]
  },
  {
   "title": "RPC Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Status per second" }
   ],
   "targets": [
    { "expr": "sum(rate(code_ok_total[30s]))", "legendFormat": "OK/s" },
    {
     "expr": "sum(rate(code_deadline_exceeded_total[30s]))",
     "legendFormat": "DE/s"
    }
   ]
  }
 ]
}