{
 "title": "Picom - Scenario 1",
 "time": { "from": "2018-04-20T09:15:00.000Z", "to": "2018-04-20T09:33:00.000Z" },
 "panels": [
  {
   "title": "Picom Server Deployment CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "alias": "Average",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" }
     ]
    },
    {
     "alias": "Sum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduling vs Metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(specific_metric)", "legendFormat": "Replicas" },
    { "expr": "avg(specific_metric)", "legendFormat": "Specific Metric" }
   ]
  },
  {
   "title": "RPC Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Status per second" }
   ],
   "targets": [
    { "expr": "sum(rate(code_ok_total[1m]))", "legendFormat": "OK/s" },
    {
     "expr": "sum(rate(code_deadline_exceeded_total[1m]))",
     "legendFormat": "DE/s"
    }
   ]
  }
 ]
}