apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: picom-client
spec:
  replicas: 4
  template:
    metadata:
      labels:
       k8s-app: picom-client
    spec:
      containers:
      - name: picom-client
        image: picoreti/picom:1
        command: ["/client.bin"]
        args: 
        - --uri=amqp://$(RABBITMQ_SERVICE_HOST):$(RABBITMQ_SERVICE_PORT_AMQP)
        # frequency of requests
        - --hz=5
        - --hz=10
        - --hz=15
        - --hz=20
        # payload size in bytes
        - --packet_size=81920
        # period publishing each frequency [in seconds]
        - --duration=240
        imagePullPolicy: Always
