apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: viros/is-rabbitmq:3
        ports:
        - name: amqp
          containerPort: 5672
        - name: managment
          containerPort: 15672
        readinessProbe:
          httpGet:
            path: /
            port: managment
          initialDelaySeconds: 3
          periodSeconds: 30 

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: managment
    protocol: TCP 
    port: 80
    targetPort: managment
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: amqp
  selector:
    k8s-app: rabbitmq
