{
 "title": "Picom",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "OK",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(code_ok_total[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Picom Server Deployment CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "alias": "Average",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" }
     ]
    },
    {
     "alias": "Sum",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" }
     ]
    }
   ]
  },
  {
   "title": "Scheduling vs Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(specific_metric)", "legendFormat": "Replicas" },
    { "expr": "avg(specific_metric)", "legendFormat": "Specific Metric" }
   ]
  },
  {
   "title": "DE",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(code_deadline_exceeded_total[1m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "#Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(specific_metric)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "cpu/usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/picom-server(.*)/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pod" }
     ]
    }
   ]
  },
  {
   "title": "Client Bandwith",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=~", "value": "/picom-client-(.*)/" }
     ]
    }
   ]
  },
  {
   "title": "RPC Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Status per second" }
   ],
   "targets": [
    { "expr": "sum(rate(code_ok_total[1m]))", "legendFormat": "OK/s" },
    {
     "expr": "sum(rate(code_deadline_exceeded_total[1m]))",
     "legendFormat": "DE/s"
    }
   ]
  },
  {
   "title": "Specific Metric",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(specific_metric)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}